// plugins/repositories.ts
import { defineNuxtPlugin } from "#app";
import { StoresRep } from "~/repository/stores";
import { SalesPlanRep } from "~/modules/profile/repository/salesPlan";
import { SalesPlanMarketplaceRep } from "~/modules/profile/repository/SalesPlanMarketPlace";
import { SalesPlanDayRep } from "~/modules/profile/repository/salesPlanDay";
import { AreasRep } from "~/modules/profile/repository/area";
import { StorageTypesRep } from "~/modules/profile/repository/storageTypes";
import { StoragesLeftRep } from "~/modules/profile/repository/storagesLeft";
import { MarketplaceLeftRep } from "~/modules/profile/repository/marketplaceLeft";
import { SalesAgentLeftRep } from "~/modules/profile/repository/salesAgentLeft";
import { LoginRep } from "~/modules/auth/repository/login";
import { UsersRep } from "~/modules/admin/modules/personal/repository/users";
import { PermissionsRep } from "~/modules/admin/modules/personal/repository/permissions";
import { IndexBalanceRep } from "~/modules/profile/repository/indexBalance";
import { PurchasesRep } from "~/modules/profile/repository/purchases";
import { SalesAgentsRep } from "~/modules/admin/modules/personal/repository/salesAgents";
import { DriversRep } from "~/modules/admin/modules/personal/repository/drivers";
import { PaymentRequestsRep } from "~/modules/admin/modules/payment/repository/paymentRequests";
import { SalesPlanSpendingRep } from "~/modules/profile/repository/salesPlanSpending";
import { CitiesRep } from "~/modules/admin/repository/cities";
import { DistrictsRep } from "~/modules/admin/repository/districts";
import { ProductsRep } from "~/modules/admin/repository/products";
import { MarketplacesRep } from "~/modules/admin/repository/marketplaces";

export default defineNuxtPlugin((nuxtApp) => {
  const salesPlanRep = new SalesPlanRep();
  const storesRep = new StoresRep();
  const salesPlanMarketplaceRep = new SalesPlanMarketplaceRep();
  const salesPlanDayRep = new SalesPlanDayRep();
  const areasRep = new AreasRep();
  const storageTypesRep = new StorageTypesRep();
  const storagesLeftRep = new StoragesLeftRep();
  const marketplaceLeftRep = new MarketplaceLeftRep();
  const salesAgentLeftRep = new SalesAgentLeftRep();
  const loginRep = new LoginRep();
  const usersRep = new UsersRep();
  const permissionsRep = new PermissionsRep();
  const indexBalanceRep = new IndexBalanceRep();
  const purchasesRep = new PurchasesRep();
  const salesAgentsRep = new SalesAgentsRep();
  const driversRep = new DriversRep();
  const paymentRequestsRep = new PaymentRequestsRep();
  const salesPlanSpendingRep = new SalesPlanSpendingRep();
  const citiesRep = new CitiesRep();
  const districtsRep = new DistrictsRep();
  const productsRep = new ProductsRep();
  const marketplacesRep = new MarketplacesRep();

  nuxtApp.provide("salesPlanRep", salesPlanRep);
  nuxtApp.provide("storesRep", storesRep);
  nuxtApp.provide("salesPlanMarketplaceRep", salesPlanMarketplaceRep);
  nuxtApp.provide("salesPlanDayRep", salesPlanDayRep);
  nuxtApp.provide("areasRep", areasRep);
  nuxtApp.provide("storageTypesRep", storageTypesRep);
  nuxtApp.provide("storagesLeftRep", storagesLeftRep);
  nuxtApp.provide("marketplaceLeftRep", marketplaceLeftRep);
  nuxtApp.provide("salesAgentLeftRep", salesAgentLeftRep);
  nuxtApp.provide("loginRep", loginRep);
  nuxtApp.provide("usersRep", usersRep);
  nuxtApp.provide("permissionsRep", permissionsRep);
  nuxtApp.provide("indexBalanceRep", indexBalanceRep);
  nuxtApp.provide("purchasesRep", purchasesRep);
  nuxtApp.provide("salesAgentsRep", salesAgentsRep);
  nuxtApp.provide("driversRep", driversRep);
  nuxtApp.provide("paymentRequestsRep", paymentRequestsRep);
  nuxtApp.provide("salesPlanSpendingRep", salesPlanSpendingRep);
  nuxtApp.provide("citiesRep", citiesRep);
  nuxtApp.provide("districtsRep", districtsRep);
  nuxtApp.provide("productsRep", productsRep);
  nuxtApp.provide("marketplacesRep", marketplacesRep);
});
