version: "3.7"

services:
  traefik:
    image: traefik:v2.9
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/ssl/:/ssl-certs/

  frontend:
    build: .
    restart: always
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.project1.rule=Host(`46.254.16.69`)"
      - "traefik.http.services.project1.loadbalancer.server.port=3000"
