interface reportDataDays {
	workDay: false;
}

interface reportDataEmployeesDays {
	status: string;
	replaced_id: number | null;
	replaced_name: string | null;
	replaced_lastName: string | null;
}

interface reportDataEmployees {
	name: string;
	lastName: string;
	department: string;
	days: Record<string, reportDataEmployeesDays>;
	totalWorkDays: number;
}

interface reportData {
	days: Record<string, reportDataDays>;
	employees: Record<number, reportDataEmployees>;
}

export const reportData: reportData = {
	days: {
		"01.09.2024": {
			workDay: false,
		},
		"02.09.2024": {
			workDay: true,
		},
		"03.09.2024": {
			workDay: true,
		},
		"04.09.2024": {
			workDay: true,
		},
		"05.09.2024": {
			workDay: true,
		},
		"06.09.2024": {
			workDay: true,
		},
		"07.09.2024": {
			workDay: false,
		},
		"08.09.2024": {
			workDay: false,
		},
		"09.09.2024": {
			workDay: true,
		},
		"10.09.2024": {
			workDay: true,
		},
		"11.09.2024": {
			workDay: true,
		},
		"12.09.2024": {
			workDay: true,
		},
		"13.09.2024": {
			workDay: true,
		},
		"14.09.2024": {
			workDay: false,
		},
		"15.09.2024": {
			workDay: false,
		},
		"16.09.2024": {
			workDay: true,
		},
		"17.09.2024": {
			workDay: true,
		},
		"18.09.2024": {
			workDay: true,
		},
		"19.09.2024": {
			workDay: true,
		},
		"20.09.2024": {
			workDay: true,
		},
		"21.09.2024": {
			workDay: false,
		},
		"22.09.2024": {
			workDay: false,
		},
		"23.09.2024": {
			workDay: true,
		},
		"24.09.2024": {
			workDay: true,
		},
		"25.09.2024": {
			workDay: true,
		},
		"26.09.2024": {
			workDay: true,
		},
		"27.09.2024": {
			workDay: true,
		},
		"28.09.2024": {
			workDay: false,
		},
		"29.09.2024": {
			workDay: false,
		},
		"30.09.2024": {
			workDay: true,
		},
		"31.09.2024": {
			workDay: true,
		},
	},
	// worked - Присутствует
	// absent - Отсутствует
	// sick_leave - Больничный
	// vocation - Отпуск
	employees: {
		1: {
			name: "Антон",
			lastName: "Никитинов",
			department: "Администратор",
			days: {
				"01.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"02.09.2024": {
					status: "absent",
					replaced_id: 2,
					replaced_name: null,
					replaced_lastName: null,
				},
				"03.09.2024": {
					status: "absent",
					replaced_id: 2,
					replaced_name: "Олег",
					replaced_lastName: "Максимов",
				},
				"04.09.2024": {
					status: "sick_leave",
					replaced_id: 2,
					replaced_name: "Олег",
					replaced_lastName: "Максимов",
				},
				"05.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"06.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"07.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"08.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"09.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"10.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"11.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"12.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"13.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"14.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"15.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"16.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"17.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"18.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"19.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"20.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"21.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"22.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"23.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"24.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"25.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"26.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"27.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"28.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"29.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"30.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"31.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
			},
			totalWorkDays: 18,
		},
		2: {
			name: "Олег",
			lastName: "Максимов",
			department: "Администратор",
			days: {
				"01.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"02.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"03.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"04.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"05.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"06.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"07.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"08.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"09.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"10.09.2024": {
					status: "absent",
					replaced_id: 1,
					replaced_name: "Антон",
					replaced_lastName: "Никитинов",
				},
				"11.09.2024": {
					status: "absent",
					replaced_id: 1,
					replaced_name: "Антон",
					replaced_lastName: "Никитинов",
				},
				"12.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"13.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"14.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"15.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"16.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"17.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"18.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"19.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"20.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"21.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"22.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"23.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"24.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"25.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"26.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"27.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"28.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"29.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"30.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"31.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
			},
			totalWorkDays: 19,
		},
		3: {
			name: "Александр",
			lastName: "Иванов",
			department: "Администратор",
			days: {
				"01.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"02.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"03.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"04.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"05.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"06.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"07.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"08.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"09.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"10.09.2024": {
					status: "vocation",
					replaced_id: 4,
					replaced_name: "Анна",
					replaced_lastName: "Смирнова",
				},
				"11.09.2024": {
					status: "vocation",
					replaced_id: 4,
					replaced_name: "Анна",
					replaced_lastName: "Смирнова",
				},
				"12.09.2024": {
					status: "vocation",
					replaced_id: 4,
					replaced_name: "Анна",
					replaced_lastName: "Смирнова",
				},
				"13.09.2024": {
					status: "vocation",
					replaced_id: 4,
					replaced_name: "Анна",
					replaced_lastName: "Смирнова",
				},
				"14.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"15.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"16.09.2024": {
					status: "vocation",
					replaced_id: 4,
					replaced_name: "Анна",
					replaced_lastName: "Смирнова",
				},
				"17.09.2024": {
					status: "vocation",
					replaced_id: 4,
					replaced_name: "Анна",
					replaced_lastName: "Смирнова",
				},
				"18.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"19.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"20.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"21.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"22.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"23.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"24.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"25.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"26.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"27.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"28.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"29.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"30.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"31.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
			},
			totalWorkDays: 15,
		},
		4: {
			name: "Анна",
			lastName: "Смирнова",
			department: "Администратор",
			days: {
				"01.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"02.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"03.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"04.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"05.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"06.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"07.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"08.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"09.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"10.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"11.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"12.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"13.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"14.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"15.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"16.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"17.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"18.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"19.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"20.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"21.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"22.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"23.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"24.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"25.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"26.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"27.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"28.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"29.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"30.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"31.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
			},
			totalWorkDays: 21,
		},
		5: {
			name: "Лилия",
			lastName: "Колякова",
			department: "Администратор",
			days: {
				"01.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"02.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"03.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"04.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"05.09.2024": {
					status: "absent",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"06.09.2024": {
					status: "absent",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"07.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"08.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"09.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"10.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"11.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"12.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"13.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"14.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"15.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"16.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"17.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"18.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"19.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"20.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"21.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"22.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"23.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"24.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"25.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"26.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"27.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"28.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"29.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"30.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"31.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
			},
			totalWorkDays: 21,
		},
		6: {
			name: "Алия",
			lastName: "Тимурова",
			department: "Администратор",
			days: {
				"01.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"02.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"03.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"04.09.2024": {
					status: "sick_leave",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"05.09.2024": {
					status: "sick_leave",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"06.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"07.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"08.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"09.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"10.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"11.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"12.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"13.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"14.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"15.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"16.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"17.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"18.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"19.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"20.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"21.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"22.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"23.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"24.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"25.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"26.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"27.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"28.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"29.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"30.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"31.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
			},
			totalWorkDays: 21,
		},
		7: {
			name: "Алина",
			lastName: "Васильевна",
			department: "Администратор",
			days: {
				"01.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"02.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"03.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"04.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"05.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"06.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"07.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"08.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"09.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"10.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"11.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"12.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"13.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"14.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"15.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"16.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"17.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"18.09.2024": {
					status: "vocation",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"19.09.2024": {
					status: "vocation",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"20.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"21.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"22.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"23.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"24.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"25.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"26.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"27.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"28.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"29.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"30.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"31.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
			},
			totalWorkDays: 21,
		},
		8: {
			name: "Полина",
			lastName: "Федорова",
			department: "Администратор",
			days: {
				"01.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"02.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"03.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"04.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"05.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"06.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"07.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"08.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"09.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"10.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"11.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"12.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"13.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"14.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"15.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"16.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"17.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"18.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"19.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"20.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"21.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"22.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"23.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"24.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"25.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"26.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"27.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"28.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"29.09.2024": {
					status: "weekend",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"30.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
				"31.09.2024": {
					status: "worked",
					replaced_id: null,
					replaced_name: null,
					replaced_lastName: null,
				},
			},
			totalWorkDays: 21,
		},
	},
};
